version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres-lab
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  gateway:
    image: gateway
    build: ./flight-booking-system/gateway/
    ports:
      - "8080:8080"
      
  cars:
    image: flight
    build: ./flight-booking-system/flight/
    ports:
      - "8060:8060"
      
  rental:
    image: ticket
    build: ./flight-booking-system/ticket/
    ports:
      - "8070:8070"
      
  payment:
    image: bonus
    build: ./flight-booking-system/bonus/
    ports:
      - "8050:8050"

volumes:
  db-data: